defaults:
  -
    scope:
      path: ""
    values:
      layout: "wiki"

markdown:   kramdown

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

